#! /bin/sh

export curdir="/usr/share/theftdeterrentguardian"
export predir=""

. ${curdir}/${predir}funcdefine

fn_define

. ${curdir}/${predir}funcutil

fn_sysExitTrap

. ${curdir}/${predir}funcreturn

fn_sysinst

. ${curdir}/${predir}funcguardian

fn_guardianstart


echo "Install Done." >> ${td_log_dir}/${td_log_file}

fn_returncode 0

