#! /bin/sh

export curdir=$(cd "$(dirname "$0")"; pwd)
export predir="theftdeterrentdaemon."

. ${curdir}/${predir}funcdefine

fn_define

. ${curdir}/${predir}funcutil

fn_sysExitTrap

. ${curdir}/${predir}funcreturn

fn_sysinst


. ${curdir}/${predir}funcdaemon

fn_daemonstart

echo "Install Done." >> ${td_log_dir}/${td_log_file}

fn_returncode 0

