#! /bin/sh

libpath=/usr/local/TheftDeterrentclient
libpython=libpython2.7.so.1.0
apppath=/opt/TheftDeterrentclient/client

if [ ! -d ${libpath} ] || [ ! -f ${libpath}/${libpython} ] ; then
    exit 1
else
    mkdir -p ${apppath}
    cp -fr ${libpath}/* ${apppath}/
fi

exit 0
