#! /bin/sh

export curdir=/var/lib/dpkg/info
export predir="theftdeterrentdaemon."

. ${curdir}/${predir}funcdefine

fn_define

export td_log_file=service.log

. ${curdir}/${predir}funcutil
. ${curdir}/${predir}funcdaemon

fn_syscreatelogdir

echo "Start daemon..." >> ${td_log_dir}/${td_log_file}

fn_daemonstart