#! /bin/sh

export curdir=/var/lib/dpkg/info
export predir="theftdeterrentclient."

. ${curdir}/${predir}funcdefine

fn_define

export td_log_file=service.log

. ${curdir}/${predir}funcutil
. ${curdir}/${predir}funcagent

fn_syscreatelogdir

echo "Stop agent..." >> ${td_log_dir}/${td_log_file}

fn_agentstop