#! /bin/sh

export curdir=/var/lib/dpkg/info
export predir="theftdeterrentguardian."

. ${curdir}/${predir}funcdefine

fn_define

export td_log_file=service.log

. ${curdir}/${predir}funcutil
. ${curdir}/${predir}funcguardian

fn_syscreatelogdir

echo "Check guardian status..." >> ${td_log_dir}/${td_log_file}

if ( fn_guardianstatus ) ; then
    return 0
else
    return 1
fi